name: "Deployment"

description: "Deploy newest code to the machine."

inputs:
  password:
    description: 'Host password'
    required: true
  folder-name:
    description: 'Project folder name'
    required: true
  module-name:
    description: '模組名稱'
    required: true
  host-name:
    description: 'Host domain or ip'
    required: true
  branch-name:
    description: 'The branch you want to checkout with'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pulling newest code and restart pm2 app
      uses: appleboy/ssh-action@v1.1.0
      with:
        command: |
          source ~/.bashrc
          node --version
          npm install -g yarn pm2
          npm add --global nx@latest
          yarn install
          nx build ${{ inputs.module-name }}
          pm2 start ./deploy/{{ inputs.module-name }}/ecosystem.config.js
        host: ${{ inputs.host-name }}
        user: root
        password: ${{ inputs.password }}
