name: "Deployment"

description: "Deploy newest code to the machine."

inputs:
  env-name:
    description: 'Project folder name'
    required: true
  folder-name:
    description: 'Project folder name'
    required: true
  db-config:
    description: 'db config json string'
    required: true
  env-value:
    description: 'env file value'
    required: true
  ssh-key:
    description: 'Ssh key for login the target machine'
    required: true
  host-name:
    description: 'Host domain or ip'
    required: true
  branch-name:
    description: 'The branch you want to checkout with'
    required: true

runs:
  using: "composite"
  steps:
    - name: Pulling newest code and restart pm2 app
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /opt/services/apps/${{ inputs.folder-name }}/
          source ~/.zshrc
          yarn install
          pm2 restart ecosystem.config.js --env ${{ inputs.env-name }}
        host: ${{ inputs.host-name }}
        user: root
        key: ${{ inputs.ssh-key }}




