name: Build Token App API

on:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/cicd-app-api.yaml'
      - 'cmd/token-app-api/**'
      - 'pkg/**'
      - 'deploy/token-app-api/**'
      - 'go.mod'
      - 'go.sum'

env:
  IMAGE_NAME: passon/token-app-api

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ env.IMAGE_NAME }}"
          TAG="develop"
          
          echo "Building image: $IMAGE_NAME:$TAG"
          
          docker build \
            --file ./deploy/token-app-api/Dockerfile \
            --tag "$IMAGE_NAME:$TAG" \
            .
          
          echo "Pushing image: $IMAGE_NAME:$TAG"
          docker push "$IMAGE_NAME:$TAG"
          
          echo "✅ Build and push completed"

