name: deploy-token-app-api-production

on:
  push:
    branches:
      - develop
# on:
#   pull_request:
#     types: 
#       - closed
#     branches:
#       - main


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: token-app-api
  DOCKER_HUB_WORKSPACE: passon
  SERVER_WORK_DIRECTORY: token-services

jobs:
  copy-file-to-server:
    # if: github.event.pull_request.merged == true
    runs-on: mac-mini-build
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Copy docker-compose and .env files to target server
    - name: sync files to server
      run: |
        kill $(cat /var/run/rsyncd.pid) || echo "kill rsync process success."
        echo "${{ secrets.TOKEN_APP_API_ENV }}" > ./apps/${{ env.IMAGE_NAME }}/.env
        rsync -avh ./apps/${{ env.IMAGE_NAME }} root@${{ secrets.DEV_BACKEND_HOST }}:/opt/services/apps/
        
  start_pm2_token-app-api-service:
    # if: github.event.pull_request.merged == true
    needs: [copy-file-to-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy newest code to dev machine
        uses: ./.github/actions/run-deploy
        with:
          env-name: prod
          folder-name: token-admin-api
          branch-name: develop
          env-value: ${{ secrets.PROD_ENV }}
          host-name: ${{ secrets.DEV_BACKEND_HOST }}
          ssh-key: ${{ secrets.SSH_KEY_PROD_VALUE }}
